title: Expense Tracker FAQ Page
description: A FAQ page for the app Expense Tracker, created by Falak Prakash.
theme: just-the-docs
url: "https://falakexpensetracker.github.io"
baseurl: "/falakexpensetracker.com"

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
logo: "/assets/images/logo.jpeg"
